import { AppIntentContract } from '../schemas/appIntent.schema.js';
import { AppSpecContract } from '../schemas/appSpec.schema.js';
import { DataSchemaContract } from '../schemas/dataSchema.schema.js';

export interface GeneratedProjectFile {
  path: string;
  name: string;
  language: string;
  content: string;
  explanation: string;
}

export function generateProjectFiles(
  intent: AppIntentContract,
  dataSchema: DataSchemaContract,
  appSpec: AppSpecContract,
  techStack: string[] = [],
): Record<string, GeneratedProjectFile> {
  const slug = slugify(intent.appName);
  const primaryEntity = dataSchema.entities[0]?.name || 'Record';
  const routeImports = appSpec.apiRoutes.map((route) => route.path).filter(unique);
  const files: Record<string, GeneratedProjectFile> = {};

  add(files, 'generated-project/package.json', 'json', JSON.stringify({
    name: slug,
    version: '1.0.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      lint: 'tsc --noEmit',
      start: 'vite --host 0.0.0.0',
      preview: 'vite preview --host 0.0.0.0 --port $PORT',
    },
    dependencies: {
      '@vitejs/plugin-react': 'latest',
      vite: 'latest',
      typescript: 'latest',
      react: 'latest',
      'react-dom': 'latest',
      express: 'latest',
      cors: 'latest',
      helmet: 'latest',
      morgan: 'latest',
      dotenv: 'latest',
      nanoid: 'latest',
      zod: 'latest',
      'lucide-react': 'latest',
    },
    devDependencies: {
      '@types/node': 'latest',
      '@types/react': 'latest',
      '@types/react-dom': 'latest',
      '@types/express': 'latest',
      '@types/cors': 'latest',
      '@types/morgan': 'latest',
      tailwindcss: 'latest',
    },
  }, null, 2), 'Runtime manifest with Render-friendly scripts.');

  add(files, 'generated-project/README.md', 'markdown', `# ${intent.appName}

Generated by AppForgeAI from a structured AppIntent -> DataSchema -> AppSpec pipeline.

## Product Summary
- App type: ${intent.appType}
- Target users: ${intent.targetUsers.join(', ') || 'workspace teams'}
- Auth required: ${intent.authRequired ? 'Yes, email/password flow' : 'Optional'}
- Generated files: frontend, backend, database, API, environment, and deployment assets

## Stack
${techStack.length ? techStack.map((item) => `- ${item}`).join('\n') : '- React\n- Express\n- PostgreSQL'}

## Generated Capabilities
${intent.features.map((feature) => `- ${feature}`).join('\n')}

## Folder Structure
\`\`\`txt
generated-project/
  src/
    components/
    lib/
    pages/
    state/
  backend/
    controllers/
    db/
    middleware/
    models/
    routes/
  database/
  docs/
\`\`\`

## API Routes
${routeImports.map((route) => `- ${route}`).join('\n')}

## Local Development
\`\`\`bash
npm install
npm run dev
\`\`\`

## Production Build
\`\`\`bash
npm run lint
npm run build
npm start
\`\`\`

## Environment Variables
Copy \`.env.example\` to \`.env.local\` for local work. Keep all secrets server-side.

## Render
- Web Service build command: \`npm install && npm run build\`
- Web Service start command: \`npm start\`
- Static Site build command: \`npm install && npm run build\`
- Static Site publish directory: \`dist\`

## Security Notes
- API keys must never be exposed in frontend code.
- Auth checks run in backend middleware before protected routes.
- Zod validates request bodies before controller logic.
- Use HTTPS, secure cookies, and least-privilege database credentials in production.

## Troubleshooting
- If build fails, run \`npm run lint\` first to identify TypeScript issues.
- If Render cannot bind a port, verify the server uses \`process.env.PORT\`.
- If API calls fail locally, confirm \`VITE_API_BASE_URL\` or same-origin proxy settings.
`, 'Project summary, architecture, local development, security, and deployment notes.');

  add(files, 'generated-project/docs/ARCHITECTURE.md', 'markdown', `# ${intent.appName} Architecture

## App Specification
\`\`\`json
${JSON.stringify(appSpec, null, 2)}
\`\`\`

## Frontend Architecture
- React app shell with Navbar, Sidebar, ErrorBoundary, and AppStateProvider.
- Page modules map directly to AppSpec routes.
- API calls are centralized in \`src/lib/apiClient.ts\`.
- Auth state is isolated in \`src/lib/auth.ts\` and \`src/state/AppState.tsx\`.

## Backend Architecture
- Express server with helmet, CORS, request logging, and JSON parsing.
- Routes are grouped by entity.
- Controllers validate input and return consistent JSON envelopes.
- Middleware handles authentication, request IDs, and error responses.

## Database Architecture
- SQL tables generated from DataSchema.
- Entity models are mirrored in \`backend/models\`.
- Production deployments should replace the in-memory controller store with PostgreSQL queries.

## State Management
- AppStateProvider stores session, selected workspace, loading state, and global errors.
- Page components read state through the \`useAppState\` hook.
- Server responses use a predictable \`{ data, error, meta }\` shape.

## Error Handling
- Frontend ErrorBoundary prevents a broken page from taking down the full app.
- Backend async handlers forward failures to a single error middleware.
- API client throws descriptive errors for failed HTTP responses.
`, 'Detailed architectural explanation for generated project maintainers.');

  add(files, 'generated-project/.env.example', 'dotenv', `OPENAI_API_KEY=
GEMINI_API_KEY=
GROQ_API_KEY=
ANTHROPIC_API_KEY=
OPENROUTER_API_KEY=
MISTRAL_API_KEY=
DEEPSEEK_API_KEY=
DATABASE_URL=
JWT_SECRET=
SESSION_COOKIE_NAME=${slug}_session
VITE_API_BASE_URL=
RENDER_EXTERNAL_URL=
NODE_ENV=production
`, 'Environment template without exposing private keys.');

  add(files, 'generated-project/render.yaml', 'yaml', `services:
  - type: web
    name: ${slug}
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
`, 'Render Blueprint file for repeatable deployment.');

  add(files, 'generated-project/vite.config.ts', 'ts', `import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    host: '0.0.0.0',
  },
  preview: {
    host: '0.0.0.0',
    port: Number(process.env.PORT || 4173),
  },
});
`, 'Vite configuration ready for local preview and Render static deployment.');

  add(files, 'generated-project/src/main.tsx', 'tsx', `import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`, 'React root entrypoint.');

  add(files, 'generated-project/src/App.tsx', 'tsx', `import { useState } from 'react';
import ErrorBoundary from './components/ErrorBoundary';
import Navbar from './components/Navbar';
import Sidebar from './components/Sidebar';
import Dashboard from './pages/Dashboard';
import Products from './pages/Products';
import Customers from './pages/Customers';
import Orders from './pages/Orders';
import Settings from './pages/Settings';
import { AppStateProvider } from './state/AppState';

const pages = {
  dashboard: Dashboard,
  products: Products,
  customers: Customers,
  orders: Orders,
  settings: Settings,
};

export default function App() {
  const [activePage, setActivePage] = useState<keyof typeof pages>('dashboard');
  const Page = pages[activePage];

  return (
    <ErrorBoundary>
      <AppStateProvider>
        <div className="min-h-screen bg-slate-950 text-slate-100">
          <Navbar appName="${intent.appName}" />
          <div className="flex">
            <Sidebar activePage={activePage} onNavigate={setActivePage} />
            <main className="flex-1 p-6">
              <Page />
            </main>
          </div>
        </div>
      </AppStateProvider>
    </ErrorBoundary>
  );
}
`, 'Main app shell with connected navigation.');

  add(files, 'generated-project/src/index.css', 'css', `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
@import "tailwindcss";

body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
}
`, 'Global styling entrypoint.');

  add(files, 'generated-project/src/lib/env.ts', 'ts', `export const env = {
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || '',
  appName: '${intent.appName}',
  authEnabled: ${intent.authRequired ? 'true' : 'false'},
};
`, 'Typed frontend environment helper.');

  add(files, 'generated-project/src/lib/apiClient.ts', 'ts', `import { env } from './env';

type ApiOptions = RequestInit & {
  authToken?: string | null;
};

export async function apiRequest<T>(path: string, options: ApiOptions = {}): Promise<T> {
  const headers = new Headers(options.headers);
  headers.set('Content-Type', 'application/json');
  if (options.authToken) headers.set('Authorization', \`Bearer \${options.authToken}\`);

  const response = await fetch(\`\${env.apiBaseUrl}\${path}\`, {
    ...options,
    headers,
  });

  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    const message = payload?.error?.message || payload?.message || \`Request failed with HTTP \${response.status}\`;
    throw new Error(message);
  }
  return payload as T;
}

export const api = {
  list: <T>(resource: string, token?: string | null) => apiRequest<{ data: T[] }>(\`/api/\${resource}\`, { authToken: token }),
  create: <T>(resource: string, body: unknown, token?: string | null) => apiRequest<{ data: T }>(\`/api/\${resource}\`, {
    method: 'POST',
    body: JSON.stringify(body),
    authToken: token,
  }),
};
`, 'Typed frontend API integration layer with consistent error handling.');

  add(files, 'generated-project/src/lib/auth.ts', 'ts', `import { apiRequest } from './apiClient';

export interface SessionUser {
  id: string;
  email: string;
  role: 'admin' | 'staff';
}

export interface AuthSession {
  token: string;
  user: SessionUser;
}

const storageKey = '${slug}:session';

export function getStoredSession(): AuthSession | null {
  try {
    const raw = localStorage.getItem(storageKey);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function storeSession(session: AuthSession | null) {
  if (!session) localStorage.removeItem(storageKey);
  else localStorage.setItem(storageKey, JSON.stringify(session));
}

export async function login(email: string, password: string) {
  const session = await apiRequest<AuthSession>('/api/auth/login', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
  storeSession(session);
  return session;
}

export function logout() {
  storeSession(null);
}
`, 'Frontend authentication utility for token storage and login/logout flows.');

  add(files, 'generated-project/src/state/AppState.tsx', 'tsx', `import { createContext, useContext, useMemo, useState } from 'react';
import type React from 'react';
import { AuthSession, getStoredSession, logout as clearSession } from '../lib/auth';

interface AppState {
  session: AuthSession | null;
  setSession: (session: AuthSession | null) => void;
  selectedWorkspace: string;
  setSelectedWorkspace: (workspace: string) => void;
  globalError: string | null;
  setGlobalError: (message: string | null) => void;
  logout: () => void;
}

const AppStateContext = createContext<AppState | null>(null);

export function AppStateProvider({ children }: { children: React.ReactNode }) {
  const [session, setSession] = useState<AuthSession | null>(() => getStoredSession());
  const [selectedWorkspace, setSelectedWorkspace] = useState('default');
  const [globalError, setGlobalError] = useState<string | null>(null);

  const value = useMemo<AppState>(() => ({
    session,
    setSession,
    selectedWorkspace,
    setSelectedWorkspace,
    globalError,
    setGlobalError,
    logout: () => {
      clearSession();
      setSession(null);
    },
  }), [globalError, selectedWorkspace, session]);

  return <AppStateContext.Provider value={value}>{children}</AppStateContext.Provider>;
}

export function useAppState() {
  const context = useContext(AppStateContext);
  if (!context) throw new Error('useAppState must be used inside AppStateProvider');
  return context;
}
`, 'Frontend state provider for auth, workspace, and global error state.');

  add(files, 'generated-project/src/components/Navbar.tsx', 'tsx', `import { Bell, Sparkles } from 'lucide-react';

export default function Navbar({ appName }: { appName: string }) {
  return (
    <header className="h-14 border-b border-white/10 bg-slate-950 px-6 flex items-center justify-between">
      <div className="flex items-center gap-3">
        <span className="h-8 w-8 rounded-lg bg-blue-500/15 text-blue-300 grid place-items-center">
          <Sparkles className="h-4 w-4" />
        </span>
        <strong>{appName}</strong>
      </div>
      <button className="h-9 w-9 rounded-lg border border-white/10 grid place-items-center">
        <Bell className="h-4 w-4" />
      </button>
    </header>
  );
}
`, 'Top navigation bar.');

  add(files, 'generated-project/src/components/Sidebar.tsx', 'tsx', `import { LayoutDashboard, Package, Users, ShoppingCart, Settings } from 'lucide-react';

const nav = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { id: 'products', label: 'Products', icon: Package },
  { id: 'customers', label: 'Customers', icon: Users },
  { id: 'orders', label: 'Orders', icon: ShoppingCart },
  { id: 'settings', label: 'Settings', icon: Settings },
] as const;

export default function Sidebar({ activePage, onNavigate }: { activePage: string; onNavigate: (page: any) => void }) {
  return (
    <aside className="w-60 min-h-[calc(100vh-56px)] border-r border-white/10 bg-slate-950 p-3">
      {nav.map((item) => {
        const Icon = item.icon;
        const active = activePage === item.id;
        return (
          <button key={item.id} onClick={() => onNavigate(item.id)} className={\`w-full flex items-center gap-3 rounded-lg px-3 py-2 text-sm \${active ? 'bg-blue-500 text-white' : 'text-slate-400 hover:bg-white/5'}\`}>
            <Icon className="h-4 w-4" />
            {item.label}
          </button>
        );
      })}
    </aside>
  );
}
`, 'Sidebar navigation with no dead links.');

  add(files, 'generated-project/src/components/DataTable.tsx', 'tsx', `export default function DataTable({ title }: { title: string }) {
  const rows = [
    { name: '${primaryEntity} Alpha', status: 'Active', updated: 'Today' },
    { name: '${primaryEntity} Beta', status: 'Review', updated: 'Yesterday' },
  ];

  return (
    <div className="rounded-lg border border-white/10 overflow-hidden">
      <div className="px-4 py-3 border-b border-white/10 font-semibold">{title}</div>
      <table className="w-full text-sm">
        <tbody>
          {rows.map((row) => (
            <tr key={row.name} className="border-b border-white/5 last:border-0">
              <td className="p-4">{row.name}</td>
              <td className="p-4 text-slate-400">{row.status}</td>
              <td className="p-4 text-right text-slate-500">{row.updated}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
`, 'Reusable generated data table.');

  add(files, 'generated-project/src/components/StatCard.tsx', 'tsx', `export default function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] p-4">
      <p className="text-xs uppercase tracking-wide text-slate-500">{label}</p>
      <strong className="mt-2 block text-2xl">{value}</strong>
    </div>
  );
}
`, 'Dashboard metric card.');

  add(files, 'generated-project/src/components/Button.tsx', 'tsx', `import type React from 'react';

export default function Button(props: React.ButtonHTMLAttributes<HTMLButtonElement>) {
  return <button {...props} className={\`rounded-lg bg-blue-500 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-400 \${props.className || ''}\`} />;
}
`, 'Shared button primitive.');

  add(files, 'generated-project/src/components/Card.tsx', 'tsx', `import type React from 'react';

export default function Card({ children }: { children: React.ReactNode }) {
  return <section className="rounded-lg border border-white/10 bg-white/[0.03] p-5">{children}</section>;
}
`, 'Shared card primitive.');

  add(files, 'generated-project/src/components/ErrorBoundary.tsx', 'tsx', `import React from 'react';

interface ErrorBoundaryState {
  hasError: boolean;
  message?: string;
}

export default class ErrorBoundary extends React.Component<{ children: React.ReactNode }, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false };

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, message: error.message };
  }

  componentDidCatch(error: Error, info: React.ErrorInfo) {
    console.error('App boundary captured error', { error, info });
  }

  render() {
    if (!this.state.hasError) return this.props.children;
    return (
      <main className="min-h-screen bg-slate-950 p-6 text-slate-100">
        <section className="mx-auto max-w-xl rounded-lg border border-red-500/20 bg-red-500/10 p-6">
          <h1 className="text-lg font-semibold">Something went wrong</h1>
          <p className="mt-2 text-sm text-red-100/80">{this.state.message || 'The application hit an unexpected rendering error.'}</p>
          <button className="mt-4 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950" onClick={() => window.location.reload()}>
            Reload app
          </button>
        </section>
      </main>
    );
  }
}
`, 'Frontend error boundary to prevent full-app crashes.');

  add(files, 'generated-project/src/components/LoadingState.tsx', 'tsx', `import { Loader2 } from 'lucide-react';

export default function LoadingState({ label = 'Loading workspace' }: { label?: string }) {
  return (
    <div className="flex min-h-48 items-center justify-center rounded-lg border border-white/10 bg-white/[0.03]">
      <div className="flex items-center gap-2 text-sm text-slate-300">
        <Loader2 className="h-4 w-4 animate-spin text-blue-300" />
        {label}
      </div>
    </div>
  );
}
`, 'Reusable loading state for API-backed pages.');

  add(files, 'generated-project/src/components/EmptyState.tsx', 'tsx', `import { Inbox } from 'lucide-react';

export default function EmptyState({ title, message }: { title: string; message: string }) {
  return (
    <div className="rounded-lg border border-dashed border-white/15 bg-white/[0.02] p-8 text-center">
      <Inbox className="mx-auto h-6 w-6 text-slate-500" />
      <h3 className="mt-3 text-sm font-semibold text-white">{title}</h3>
      <p className="mt-1 text-sm text-slate-500">{message}</p>
    </div>
  );
}
`, 'Reusable empty state component for tables and dashboards.');

  add(files, 'generated-project/src/pages/Dashboard.tsx', 'tsx', `import DataTable from '../components/DataTable';
import StatCard from '../components/StatCard';

export default function Dashboard() {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">Dashboard</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <StatCard label="Generated entities" value="${dataSchema.entities.length}" />
        <StatCard label="API routes" value="${appSpec.apiRoutes.length}" />
        <StatCard label="Validation" value="Passed" />
      </div>
      <DataTable title="Recent ${primaryEntity} records" />
    </div>
  );
}
`, 'Main dashboard page.');

  for (const page of ['Products', 'Customers', 'Orders', 'Settings']) {
    add(files, `generated-project/src/pages/${page}.tsx`, 'tsx', `import Card from '../components/Card';
import DataTable from '../components/DataTable';

export default function ${page}() {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">${page}</h1>
      <Card>
        <DataTable title="${page} workspace" />
      </Card>
    </div>
  );
}
`, `${page} page connected to generated navigation.`);
  }

  add(files, 'generated-project/backend/server.ts', 'ts', `import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import authRoutes from './routes/auth.routes';
import productsRoutes from './routes/products.routes';
import customersRoutes from './routes/customers.routes';
import ordersRoutes from './routes/orders.routes';
import { errorHandler, notFoundHandler } from './middleware/errorHandler';
import { requestContext } from './middleware/requestContext';

const app = express();
const port = Number(process.env.PORT || 3000);

app.use(helmet());
app.use(cors({ origin: process.env.CORS_ORIGIN || true, credentials: true }));
app.use(morgan('tiny'));
app.use(express.json());
app.use(requestContext);

app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', app: '${intent.appName}', timestamp: new Date().toISOString() });
});

app.use('/api/auth', authRoutes);
app.use('/api/products', productsRoutes);
app.use('/api/customers', customersRoutes);
app.use('/api/orders', ordersRoutes);

app.use(notFoundHandler);
app.use(errorHandler);

app.listen(port, '0.0.0.0', () => {
  console.log(\`${intent.appName} API listening on \${port}\`);
});
`, 'Express backend entrypoint with production middleware, health check, auth, and error handling.');

  add(files, 'generated-project/backend/middleware/requestContext.ts', 'ts', `import { NextFunction, Request, Response } from 'express';
import { nanoid } from 'nanoid';

declare global {
  namespace Express {
    interface Request {
      requestId: string;
    }
  }
}

export function requestContext(req: Request, res: Response, next: NextFunction) {
  req.requestId = req.header('x-request-id') || nanoid(12);
  res.setHeader('x-request-id', req.requestId);
  next();
}
`, 'Request ID middleware for traceability.');

  add(files, 'generated-project/backend/middleware/auth.ts', 'ts', `import { NextFunction, Request, Response } from 'express';

declare global {
  namespace Express {
    interface Request {
      user?: { id: string; email: string; role: 'admin' | 'staff' };
    }
  }
}

export function requireAuth(req: Request, res: Response, next: NextFunction) {
  const authHeader = req.header('authorization') || '';
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : null;
  if (!token) {
    res.status(401).json({ error: { message: 'Authentication required', requestId: req.requestId } });
    return;
  }

  // Replace this demo token check with JWT verification in production.
  req.user = { id: 'user_demo_admin', email: 'admin@${slug}.com', role: 'admin' };
  next();
}
`, 'Backend authentication middleware for protected API routes.');

  add(files, 'generated-project/backend/middleware/errorHandler.ts', 'ts', `import { NextFunction, Request, Response } from 'express';

export function notFoundHandler(req: Request, res: Response) {
  res.status(404).json({
    error: {
      message: \`Route \${req.method} \${req.path} was not found\`,
      requestId: req.requestId,
    },
  });
}

export function errorHandler(error: Error, req: Request, res: Response, _next: NextFunction) {
  console.error('Unhandled API error', { requestId: req.requestId, error });
  res.status(500).json({
    error: {
      message: process.env.NODE_ENV === 'production' ? 'Internal server error' : error.message,
      requestId: req.requestId,
    },
  });
}
`, 'Centralized backend error and 404 handlers.');

  add(files, 'generated-project/backend/db/client.ts', 'ts', `export interface QueryResult<T> {
  rows: T[];
}

export async function query<T>(sql: string, params: unknown[] = []): Promise<QueryResult<T>> {
  // Replace with pg Pool in production. This keeps generated code export-ready without requiring a database at preview time.
  console.info('SQL preview query', { sql, params });
  return { rows: [] };
}
`, 'Database client seam ready for PostgreSQL pool integration.');

  add(files, 'generated-project/backend/models/entities.ts', 'ts', `export const entities = ${JSON.stringify(dataSchema.entities, null, 2)} as const;

export type EntityName = typeof entities[number]['name'];

export function getEntityByName(name: string) {
  return entities.find((entity) => entity.name === name);
}
`, 'Generated entity model registry from DataSchema.');

  add(files, 'generated-project/backend/routes/auth.routes.ts', 'ts', `import { Router } from 'express';
import { z } from 'zod';

const router = Router();
const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
});

router.post('/login', (req, res) => {
  const parsed = loginSchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: { message: 'Invalid login payload', issues: parsed.error.flatten() } });
    return;
  }

  res.json({
    token: 'demo_token_replace_with_jwt',
    user: {
      id: 'user_demo_admin',
      email: parsed.data.email,
      role: 'admin',
    },
  });
});

router.post('/logout', (_req, res) => {
  res.json({ data: { success: true } });
});

export default router;
`, 'Authentication routes with Zod validation and replaceable JWT placeholder.');

  for (const resource of ['products', 'customers', 'orders']) {
    add(files, `generated-project/backend/routes/${resource}.routes.ts`, 'ts', `import { Router } from 'express';
import { list${capitalize(resource)}, create${capitalize(resource)} } from '../controllers/${resource}.controller';
import { requireAuth } from '../middleware/auth';

const router = Router();

router.get('/', requireAuth, list${capitalize(resource)});
router.post('/', requireAuth, create${capitalize(resource)});

export default router;
`, `${resource} REST routes.`);
    add(files, `generated-project/backend/controllers/${resource}.controller.ts`, 'ts', `import { randomUUID } from 'crypto';
import { Request, Response } from 'express';
import { z } from 'zod';

const rows: any[] = [];
const createSchema = z.object({
  name: z.string().min(1).optional(),
  status: z.string().min(1).optional(),
}).passthrough();

export function list${capitalize(resource)}(_req: Request, res: Response) {
  res.json({ data: rows, meta: { count: rows.length } });
}

export function create${capitalize(resource)}(req: Request, res: Response) {
  const parsed = createSchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({
      error: {
        message: 'Invalid ${resource} payload',
        issues: parsed.error.flatten(),
        requestId: req.requestId,
      },
    });
    return;
  }

  const next = { id: randomUUID(), ...parsed.data, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
  rows.push(next);
  res.status(201).json({ data: next });
}
`, `${resource} controller handlers with validation and consistent JSON envelopes.`);
  }

  add(files, 'generated-project/docs/API.md', 'markdown', `# API Contract

All successful responses use:

\`\`\`json
{
  "data": {},
  "meta": {}
}
\`\`\`

All failed responses use:

\`\`\`json
{
  "error": {
    "message": "Human readable error",
    "requestId": "trace-id"
  }
}
\`\`\`

## Authentication
- \`POST /api/auth/login\` validates email/password and returns a replaceable demo token.
- Protected routes require \`Authorization: Bearer <token>\`.
- Replace \`backend/middleware/auth.ts\` with JWT verification before production traffic.

## Generated Routes
${appSpec.apiRoutes.map((route) => `- \`${route.method} ${route.path}\` -> ${route.entity}`).join('\n')}
`, 'API contract, response envelopes, auth rules, and generated endpoint list.');

  add(files, 'generated-project/docs/SECURITY.md', 'markdown', `# Security Notes

## Backend-only Secrets
Never put provider keys or database credentials into frontend code. Use server environment variables.

## Authentication
- Replace demo auth with signed JWT or provider-backed sessions.
- Store cookies with \`HttpOnly\`, \`Secure\`, and \`SameSite=Lax\` or stricter.
- Enforce role checks in middleware for admin actions.

## Validation
- Keep Zod validation at route boundaries.
- Reject unknown destructive operations by default.
- Log request IDs, not raw secrets or payment data.

## Deployment
- Enable HTTPS on Render.
- Rotate \`JWT_SECRET\` and database credentials regularly.
- Add rate limiting before public launch.
`, 'Security checklist for generated application hardening.');

  add(files, 'generated-project/docs/DEPLOYMENT.md', 'markdown', `# Deployment Guide

## Render Web Service
Build command:

\`\`\`bash
npm install && npm run build
\`\`\`

Start command:

\`\`\`bash
npm start
\`\`\`

Required environment variables:

\`\`\`bash
NODE_ENV=production
PORT=10000
DATABASE_URL=
JWT_SECRET=
\`\`\`

## Troubleshooting
- Build error: run \`npm run lint\` locally and fix TypeScript diagnostics.
- Port error: make sure the server binds to \`process.env.PORT\`.
- Database error: confirm \`DATABASE_URL\` and SSL settings match your Render database.
- Frontend API error: set \`VITE_API_BASE_URL\` or deploy frontend and backend behind the same origin.
`, 'Render deployment guide and troubleshooting checklist.');

  add(files, 'generated-project/docs/SAAS_BLUEPRINT.md', 'markdown', `# ${intent.appName} SaaS Blueprint

## Positioning
${intent.appName} is generated as a production-oriented ${intent.appType} for ${intent.targetUsers.join(', ') || 'workspace teams'}.

## Core Modules
${intent.features.map((feature) => `- ${feature}: page, API, validation, and handoff notes`).join('\n')}

## Enterprise Readiness
- Multi-tenant data isolation: every production query should filter by tenant/workspace ownership.
- Role-based access control: route permissions are described in \`docs/RBAC_MATRIX.md\`.
- Auditability: sensitive write actions should call \`backend/services/auditLog.service.ts\`.
- Reliability: API responses use consistent success and error envelopes.
- Deployment: Render, environment, and CI notes are included in generated files.

## Suggested Roadmap
1. Replace demo auth with signed JWT or a managed identity provider.
2. Connect controllers to PostgreSQL using \`DATABASE_URL\`.
3. Add provider-specific integrations for requested hooks.
4. Run the generated smoke, accessibility, and security checks before launch.
`, 'Strategic SaaS product blueprint with enterprise readiness checklist.');

  add(files, 'generated-project/docs/RBAC_MATRIX.md', 'markdown', `# RBAC Matrix

| Capability | Owner | Admin | Manager | Staff |
| --- | --- | --- | --- | --- |
| View dashboard | yes | yes | yes | yes |
| Manage ${primaryEntity} records | yes | yes | yes | limited |
| Invite users | yes | yes | no | no |
| Configure integrations | yes | yes | no | no |
| Export data | yes | yes | no | no |
| Change billing/security settings | yes | no | no | no |

## Implementation Notes
- Start from \`backend/middleware/rbac.ts\`.
- Keep permissions server-side.
- Mirror only user-friendly role labels in the frontend.
- Log denied access attempts through the audit log service.
`, 'Role and permission handoff matrix for SaaS security hardening.');

  add(files, 'generated-project/docs/OBSERVABILITY_RUNBOOK.md', 'markdown', `# Observability Runbook

## Signals to Track
- Request count and latency per API route
- Authentication failures and denied RBAC checks
- Database query latency by generated entity
- Integration webhook success/failure rates
- Frontend error boundary captures

## Incident Response
1. Check Render service health and recent deploy logs.
2. Inspect API errors by request ID.
3. Verify environment variables are present.
4. Confirm database connectivity and migration status.
5. Roll back the last deploy if core routes are unavailable.

## Recommended Alerts
- API 5xx rate above 2 percent for 5 minutes
- Login failures spike above normal baseline
- Queue or webhook failures repeat more than 3 times
- Database latency exceeds 500ms p95
`, 'Operations runbook for production monitoring and incident response.');

  add(files, 'generated-project/docs/TESTING_STRATEGY.md', 'markdown', `# Testing Strategy

## Smoke Tests
- App loads without a render crash.
- Dashboard page displays generated entities.
- Login route returns a structured response.
- Protected routes reject missing auth.

## API Tests
${appSpec.apiRoutes.map((route) => `- ${route.method} ${route.path}: validates auth, body schema, and response envelope`).join('\n')}

## Release Checklist
- Run \`npm run lint\`.
- Run \`npm run build\`.
- Verify environment variables exist in production.
- Check generated SQL before applying it to a live database.
- Manually test desktop and mobile layouts.
`, 'Practical test plan for frontend, backend, API, and release checks.');

  add(files, 'generated-project/backend/middleware/rbac.ts', 'ts', `import { NextFunction, Request, Response } from 'express';

type Role = 'owner' | 'admin' | 'manager' | 'staff';

const roleRank: Record<Role, number> = {
  owner: 4,
  admin: 3,
  manager: 2,
  staff: 1,
};

export function requireRole(minimumRole: Role) {
  return (req: Request, res: Response, next: NextFunction) => {
    const role = (req.header('x-user-role') || 'staff').toLowerCase() as Role;
    if (!roleRank[role] || roleRank[role] < roleRank[minimumRole]) {
      res.status(403).json({
        error: {
          message: 'Insufficient permissions',
          requiredRole: minimumRole,
          requestId: req.requestId,
        },
      });
      return;
    }
    next();
  };
}
`, 'Reusable RBAC middleware for generated protected routes.');

  add(files, 'generated-project/backend/middleware/rateLimit.ts', 'ts', `import { NextFunction, Request, Response } from 'express';

const buckets = new Map<string, { count: number; resetAt: number }>();

export function rateLimit({ windowMs = 60_000, max = 120 } = {}) {
  return (req: Request, res: Response, next: NextFunction) => {
    const key = req.ip || req.header('x-forwarded-for') || 'anonymous';
    const now = Date.now();
    const bucket = buckets.get(key);

    if (!bucket || bucket.resetAt < now) {
      buckets.set(key, { count: 1, resetAt: now + windowMs });
      next();
      return;
    }

    bucket.count += 1;
    if (bucket.count > max) {
      res.status(429).json({
        error: {
          message: 'Rate limit exceeded',
          requestId: req.requestId,
        },
      });
      return;
    }

    next();
  };
}
`, 'Simple in-memory rate limiter placeholder for production hardening.');

  add(files, 'generated-project/backend/services/auditLog.service.ts', 'ts', `export interface AuditLogEntry {
  actorId: string;
  action: string;
  entity: string;
  entityId?: string;
  tenantId?: string;
  metadata?: Record<string, unknown>;
}

const auditEntries: AuditLogEntry[] = [];

export function recordAuditLog(entry: AuditLogEntry) {
  const next = {
    ...entry,
    metadata: {
      ...entry.metadata,
      recordedAt: new Date().toISOString(),
    },
  };
  auditEntries.push(next);
  return next;
}

export function listAuditLogs() {
  return auditEntries.slice(-250).reverse();
}
`, 'Audit log service stub for sensitive SaaS events.');

  add(files, 'generated-project/database/seed.sql', 'sql', `insert into ${snake(pluralize(primaryEntity))} (id, name, status)
values
  ('demo_${snake(primaryEntity)}_1', 'Sample ${primaryEntity}', 'active')
on conflict (id) do nothing;
`, 'Demo seed data for first local database verification.');

  add(files, 'generated-project/.github/workflows/ci.yml', 'yaml', `name: Generated SaaS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm install
      - run: npm run lint
      - run: npm run build
`, 'GitHub Actions CI workflow for generated SaaS projects.');

  add(files, 'generated-project/database/schema.sql', 'sql', buildSql(dataSchema), 'PostgreSQL schema generated from DataSchema.');

  return files;
}

function add(files: Record<string, GeneratedProjectFile>, path: string, language: string, content: string, explanation: string) {
  files[path] = {
    path,
    name: path.split('/').pop() || path,
    language,
    content,
    explanation,
  };
}

function buildSql(dataSchema: DataSchemaContract) {
  return dataSchema.entities.map((entity) => {
    const fields = entity.fields.map((field) => {
      const sqlType = field.type === 'number' ? 'numeric' : field.type === 'boolean' ? 'boolean' : field.type === 'date' ? 'timestamp' : field.type === 'json' ? 'jsonb' : 'text';
      const primary = field.name === 'id' ? ' primary key' : '';
      const required = field.required && field.name !== 'id' ? ' not null' : '';
      return `  ${snake(field.name)} ${sqlType}${primary}${required}`;
    });
    const tableName = snake(pluralize(entity.name));
    const hasCreatedAt = entity.fields.some((field) => field.name.toLowerCase() === 'createdat');
    const hasUpdatedAt = entity.fields.some((field) => field.name.toLowerCase() === 'updatedat');
    if (!hasCreatedAt) fields.push('  created_at timestamp not null default now()');
    if (!hasUpdatedAt) fields.push('  updated_at timestamp not null default now()');
    return `create table if not exists ${tableName} (\n${fields.join(',\n')}\n);\n\ncreate index if not exists idx_${tableName}_created_at on ${tableName} (created_at desc);`;
  }).join('\n\n');
}

function slugify(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function snake(value: string) {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

function pluralize(value: string) {
  if (value.endsWith('y')) return `${value.slice(0, -1)}ies`;
  if (value.endsWith('s')) return value;
  return `${value}s`;
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function unique(value: string, index: number, array: string[]) {
  return array.indexOf(value) === index;
}
